server:
  error:
    include-message: always

spring:
  main:
    banner-mode: off
  devtools:
    add-properties: false
  application:
    name: mini-autorizador
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/miniautorizador
    hikari:
      maximumPoolSize: 5
      connectionTimeout: 5000
      connection-init-sql: "SET time_zone = 'America/Sao_Paulo'"
  jpa:
    show-sql: true
    open-in-view: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: info, health

logging:
  level:
    root: info
