version: "3.7"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: miniautorizador
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"